# Generated by Django 2.2.6 on 2019-10-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_remove_post_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
